const langs={
    en:"English",
    bn:"বাংলা",
    bs:"Bosanski",
    "zh_CN#Hans":"中文",
    fr:"Français",
    ca:"Català",
    es_ES:"Español",
    cs:"Čeština",
    da:"Dansk",
    nl:"Dutch",
    de:"Deutsch",
    el:"Ελληνικά",
    bg:"Български",
    et:"Eesti",
    fi:"Suomi",
    hi:"हिन्दी",
    hu:"Magyar",
    it:"Italiano",
    id:"Indonesian",
    ja:"日本語",
    ko:"한국어",
    lt:"Lietuvių",
    lv:"Latviešu",
    ms:"Melayu",
    nb:"Norsk",
    pl:"Polski",
    pt:"Português",
    ro:"Română",
    ru:"Русский",
    sv:"Svenska",
    th:"ภาษาไทย",
    tr:"Türkçe",
    uk:"украї́нська",
    vi:"Tiếng Việt"
}

export { langs }